# Generated by Django 4.0.5 on 2022-07-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='gustos',
            field=models.CharField(default='Some String', max_length=50),
        ),
        migrations.AddField(
            model_name='perro',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
