# Generated by Django 4.0.5 on 2022-07-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_perro_gustos_perro_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='gustos',
            field=models.CharField(max_length=50),
        ),
    ]
